import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import SidequestCard from "@/app/sidequest-card";
import { getPublicSidequest } from "@/lib/sidequest-data";
import type { VoteValue } from "@/lib/sidequests";
import { createServerSupabaseClient } from "@/lib/supabase-server";

export const dynamic = "force-dynamic";

type SidequestPageProps = {
  params: Promise<{ id: string }>;
};

export default async function SidequestPage({ params }: SidequestPageProps) {
  const { id } = await params;
  const supabase = await createServerSupabaseClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) redirect(`/login?next=/sidequests/${id}`);

  const sidequest = await getPublicSidequest(id);

  if (!sidequest) notFound();
  let currentVote: VoteValue | null = null;

  const { data } = await supabase
    .from("votes")
    .select("value")
    .eq("sidequest_id", sidequest.id)
    .maybeSingle();
  currentVote = (data?.value as VoteValue | undefined) ?? null;

  return (
    <main className="page detail-page">
      <Link href="/#feed" className="back-link">← Back to the feed</Link>
      <SidequestCard
        sidequest={sidequest}
        currentVote={currentVote}
        detailed
      />
      <aside className="ai-note">
        <strong>Before you head out</strong>
        <p>This plan was generated by AI. Verify current hours, prices, transit, accessibility, and local conditions yourself.</p>
      </aside>
    </main>
  );
}
